"""Add archiving and user tracking to notifications

Revision ID: 1403b69f32b7
Revises: ed7329eac025
Create Date: 2026-01-17 16:20:28.025897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1403b69f32b7'
down_revision = 'ed7329eac025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('revenue_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'revenues', ['revenue_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'credits', ['credit_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('archived')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('revenue_id')
        batch_op.drop_column('credit_id')

    # ### end Alembic commands ###
