"""Add logo_data and logo_mime_type fields to Category and Service models

Revision ID: 1a1c4bba4820
Revises: ab117d0d41e9
Create Date: 2026-01-10 07:16:45.700984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1c4bba4820'
down_revision = 'ab117d0d41e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('logo_mime_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('logo_mime_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('logo_mime_type')
        batch_op.drop_column('logo_data')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('logo_mime_type')
        batch_op.drop_column('logo_data')

    # ### end Alembic commands ###
