"""add_card_purchases_table

Revision ID: 1c7fdfad036e
Revises: e9c3db0655d7
Create Date: 2026-01-23 18:49:06.941130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7fdfad036e'
down_revision = 'e9c3db0655d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receipt_image_data', sa.LargeBinary(), nullable=True),
    sa.Column('receipt_image_name', sa.String(length=255), nullable=True),
    sa.Column('receipt_image_mime_type', sa.String(length=100), nullable=True),
    sa.Column('receipt_image_size', sa.Integer(), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('was_manually_edited', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_purchases_purchase_date'), ['purchase_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_purchases_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_purchases_user_id'))
        batch_op.drop_index(batch_op.f('ix_card_purchases_purchase_date'))

    op.drop_table('card_purchases')
    # ### end Alembic commands ###
