"""Add payment_type field to CardPurchase

Revision ID: 26b6b36e09ca
Revises: 56577338f302
Create Date: 2026-02-04 08:19:11.627130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26b6b36e09ca'
down_revision = '56577338f302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    with op.batch_alter_table('card_purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=50), nullable=True))

    # Update existing rows to have default value 'card'
    op.execute("UPDATE card_purchases SET payment_type = 'card' WHERE payment_type IS NULL")

    # Now make the column NOT NULL
    with op.batch_alter_table('card_purchases', schema=None) as batch_op:
        batch_op.alter_column('payment_type', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_purchases', schema=None) as batch_op:
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
