"""Add date_of_birth to Subscription model

Revision ID: 425ee8d71e41
Revises: 84b3b70b0704
Create Date: 2026-01-17 07:19:32.906160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425ee8d71e41'
down_revision = '84b3b70b0704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
