"""add trial period support

Revision ID: 4b5a5262087f
Revises: 8a0c86d3905f
Create Date: 2026-01-02 06:37:00.371008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5a5262087f'
down_revision = '8a0c86d3905f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_start_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('trial_start_date')

    # ### end Alembic commands ###
