"""add company field to revenues

Revision ID: 4dbcec93a2c8
Revises: afbff896a8a8
Create Date: 2026-01-14 21:41:37.177598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbcec93a2c8'
down_revision = 'afbff896a8a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revenues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revenues', schema=None) as batch_op:
        batch_op.drop_column('company')

    # ### end Alembic commands ###
