"""Add name_en to categories

Revision ID: 56577338f302
Revises: 930d55f6d6a8
Create Date: 2026-02-03 21:28:46.695246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56577338f302'
down_revision = '930d55f6d6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('name_en')

    # ### end Alembic commands ###
