"""Add updated_at to Category and Service models

Revision ID: 66952aa68532
Revises: 1a1c4bba4820
Create Date: 2026-01-10 13:03:16.215016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66952aa68532'
down_revision = '1a1c4bba4820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
