"""Add reminder_id to notifications table

Revision ID: 693ffc343ce0
Revises: cd94b30e6bd3
Create Date: 2026-01-25 10:38:12.627332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693ffc343ce0'
down_revision = 'cd94b30e6bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'reminders', ['reminder_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reminder_id')

    # ### end Alembic commands ###
