"""add_english_descriptions_to_credit_types

Revision ID: 77ca8a003f84
Revises: bd6057eae65d
Create Date: 2026-02-03 14:32:50.632551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ca8a003f84'
down_revision = 'bd6057eae65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_types', schema=None) as batch_op:
        batch_op.drop_column('description_en')

    # ### end Alembic commands ###
