"""Add billing_period to plans and Premium Annual plan

Revision ID: 78396f74e9e7
Revises: 0abd7d9f8240
Create Date: 2025-12-30 23:27:07.496896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78396f74e9e7'
down_revision = '0abd7d9f8240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_period', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('billing_period')

    # ### end Alembic commands ###
