"""Add storage_limit to User model

Revision ID: 7e2a72e3bc12
Revises: 5697eac69a5c
Create Date: 2026-01-22 22:03:55.131613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2a72e3bc12'
down_revision = '5697eac69a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_limit', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('storage_limit')

    # ### end Alembic commands ###
