"""add_name_en_to_credit_types

Revision ID: 930d55f6d6a8
Revises: 77ca8a003f84
Create Date: 2026-02-03 14:45:25.683065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930d55f6d6a8'
down_revision = '77ca8a003f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_types', schema=None) as batch_op:
        batch_op.drop_column('name_en')

    # ### end Alembic commands ###
