"""remove plan cancellation fields for immediate downgrade

Revision ID: a4784daf5997
Revises: f1e1984ba151
Create Date: 2026-01-02 18:24:25.119702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4784daf5997'
down_revision = 'f1e1984ba151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('plan_period_end_date')
        batch_op.drop_column('plan_cancel_at_period_end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_cancel_at_period_end', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('plan_period_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
