"""Add default_currency to User model

Revision ID: ab9b8893f571
Revises: c3ea193ee76b
Create Date: 2025-12-31 18:03:50.552695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9b8893f571'
down_revision = 'c3ea193ee76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notifications_subscription_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscriptions', ['subscription_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_currency', sa.String(length=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_currency')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_subscription_id_fkey'), 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
