"""Add default_banks table for pre-configured banks

Revision ID: afe0b4bf5d67
Revises: 62e5b6b48a93
Create Date: 2026-02-08 00:03:17.727474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe0b4bf5d67'
down_revision = '62e5b6b48a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('logo_data', sa.Text(), nullable=True),
    sa.Column('logo_mime_type', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('initials', sa.String(length=10), nullable=True),
    sa.Column('text_color', sa.String(length=7), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('default_banks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_default_banks_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_default_banks_language'), ['language'], unique=False)

    # Ajouter les banques françaises par défaut
    from datetime import datetime
    default_banks = [
        {'name': 'BNP Paribas', 'color': '#00965E', 'initials': 'BNP', 'bic': 'BNPAFRPP', 'text_color': '#FFFFFF'},
        {'name': 'Crédit Agricole', 'color': '#00965E', 'initials': 'CA', 'bic': 'AGRIFRPP', 'text_color': '#FFFFFF'},
        {'name': 'Société Générale', 'color': '#E30513', 'initials': 'SG', 'bic': 'SOGEFRPP', 'text_color': '#FFFFFF'},
        {'name': 'Crédit Mutuel', 'color': '#003D7A', 'initials': 'CM', 'bic': 'CMCIFRPP', 'text_color': '#FFFFFF'},
        {'name': 'Banque Postale', 'color': '#FFD200', 'initials': 'LBP', 'bic': 'PSSTFRPP', 'text_color': '#003D7A'},
        {'name': 'Caisse d''Épargne', 'color': '#00965E', 'initials': 'CE', 'bic': 'CEPAFRPP', 'text_color': '#FFFFFF'},
        {'name': 'LCL', 'color': '#003D7A', 'initials': 'LCL', 'bic': 'CRLYFRPP', 'text_color': '#FFFFFF'},
        {'name': 'CIC', 'color': '#003D7A', 'initials': 'CIC', 'bic': 'CMCIFRPP', 'text_color': '#FFFFFF'},
        {'name': 'BoursoBank', 'color': '#0E52A0', 'initials': 'BRS', 'bic': 'BOUSFRPP', 'text_color': '#FFFFFF'},
        {'name': 'Banque Populaire', 'color': '#E30513', 'initials': 'BP', 'bic': 'CCBPFRPP', 'text_color': '#FFFFFF'},
        {'name': 'Hello bank!', 'color': '#FF6600', 'initials': 'HB', 'bic': 'BNPAFRPP', 'text_color': '#FFFFFF'},
        {'name': 'ING Direct', 'color': '#FF6200', 'initials': 'ING', 'bic': 'INGBFRPP', 'text_color': '#FFFFFF'},
        {'name': 'Fortuneo', 'color': '#8B0000', 'initials': 'FTN', 'bic': 'FTNOFRP1', 'text_color': '#FFFFFF'},
        {'name': 'Monabanq', 'color': '#00A651', 'initials': 'MNB', 'bic': 'CMCIFRPP', 'text_color': '#FFFFFF'},
        {'name': 'N26', 'color': '#36A18B', 'initials': 'N26', 'bic': 'NTSBDEB1', 'text_color': '#FFFFFF'},
        {'name': 'Revolut', 'color': '#0075EB', 'initials': 'RVL', 'bic': 'REVOGB21', 'text_color': '#FFFFFF'},
    ]

    # Utiliser la méthode bulk_insert pour éviter les problèmes d'échappement
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, Boolean, DateTime

    default_banks_table = table('default_banks',
        column('name', String),
        column('country_code', String),
        column('language', String),
        column('color', String),
        column('initials', String),
        column('bic', String),
        column('text_color', String),
        column('is_active', Boolean),
    )

    for bank_data in default_banks:
        op.execute(
            default_banks_table.insert().values(
                name=bank_data['name'],
                country_code='FR',
                language='fr',
                color=bank_data['color'],
                initials=bank_data['initials'],
                bic=bank_data['bic'],
                text_color=bank_data['text_color'],
                is_active=True
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('default_banks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_default_banks_language'))
        batch_op.drop_index(batch_op.f('ix_default_banks_country_code'))

    op.drop_table('default_banks')
    # ### end Alembic commands ###
