"""Update providers table - replace contact_info with provider_type, phone and email

Revision ID: cd94b30e6bd3
Revises: c17c77c7e8cc
Create Date: 2026-01-25 00:37:26.947345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd94b30e6bd3'
down_revision = 'c17c77c7e8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_type', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.drop_column('contact_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('provider_type')

    # ### end Alembic commands ###
