"""add_installment_payment_id_to_notifications

Revision ID: d38cdcdb8654
Revises: b25494fc3fa8
Create Date: 2026-01-17 17:43:20.887510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38cdcdb8654'
down_revision = 'b25494fc3fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_payment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'installment_payments', ['installment_payment_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('installment_payment_id')

    # ### end Alembic commands ###
