"""add_product_category_to_installment_payments

Revision ID: de28f2685e23
Revises: d38cdcdb8654
Create Date: 2026-01-17 17:49:21.207066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de28f2685e23'
down_revision = 'd38cdcdb8654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installment_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installment_payments', schema=None) as batch_op:
        batch_op.drop_column('product_category')

    # ### end Alembic commands ###
