"""set subscription_id to null on delete instead of cascade delete

Revision ID: ed7329eac025
Revises: f92fa4d7270f
Create Date: 2026-01-17 14:04:58.194431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7329eac025'
down_revision = 'f92fa4d7270f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notifications_subscription_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_subscription_id_fkey'), 'subscriptions', ['subscription_id'], ['id'])

    # ### end Alembic commands ###
