"""add plan cancellation fields

Revision ID: f1e1984ba151
Revises: b124d467e25c
Create Date: 2026-01-02 13:27:30.873051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e1984ba151'
down_revision = 'b124d467e25c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_cancel_at_period_end', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('plan_period_end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('plan_period_end_date')
        batch_op.drop_column('plan_cancel_at_period_end')

    # ### end Alembic commands ###
